name: Check Code

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check for clean Notebooks
      uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
